# Generated by Django 5.2.6 on 2025-09-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=250)),
                ('imagem', models.ImageField(upload_to='media/')),
                ('data_hora_public', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('user', models.CharField(max_length=10)),
                ('nome_perfil', models.CharField(max_length=20)),
            ],
        ),
    ]
